server:
    port: 18001

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://k9d103a.p.ssafy.io:18761/eureka/

spring:
    application:
        name: apigateway
#    cloud:
#        gateway:
#            routes:
#                - id: relation-service
#                  uri: lb://RELATION-SERVICE
#                  predicates:
#                      - Path=/api/relation/**
#                - id: mission-service
#                  uri: lb://MISSION-SERVICE
#                  predicates:
#                    - path=/api/mission/**